### ISSUE TITLE
accessing LinkedIn Skills API

### ISSUE THREAD

**Issue by steventsimpson** [mpiccirilli/Rlinkedin#16]
Hi Michael,

I came across your RLinkedIn package. I see that it doesn't currently access the Skills API, but it does access the People API. 

Based on this Quora post, I see that as of Dec 2015 LinkedIn's API exposes end points to the Endorsement API. I'm wondering if your package could find a specific person and then post Endorsements to their API. 

Thanks,

Steve

**Comment by mpiccirilli** [comment]
@data-steve it might, I haven't checked the documentation in a while though because I can't access any other endpoints except the three they left open to the public -- I'd want to validate the functionality is correct before implementing it into the package.  In order to access almost all the endpoints LinkedIn (annoyingly) requires you to be accepted to their partners program (even more annoyingly, I was rejected).  If you have access, I'd be more than happy to accept pull requests into the package so it's more up-to-date.

**Comment by steventsimpson** [comment]
Thanks!

~ Steve

Sent via telepathy

**Comment by mpiccirilli** [comment]
Closing because I cannot validate.
