### ISSUE TITLE
Browse Connections

### ISSUE THREAD

**Issue by YumnaBatool** [mpiccirilli/Rlinkedin#3]
I am able to get my connections but I am unable to get second degree connections. I need to integrate it in my application.
The only way to use getMyConnections is,

> my.connections <- getMyConnections(in.auth)

It is mentioned that in the description that one can browse connections to get second degree connections (connections of connections) but I am unable to find a way to do so.
Can you please help me in this...

**Comment by mpiccirilli** [comment]
@YumnaBatool sorry for the misunderstanding, you **cannot** browse connections.  

However, you can search for people using specific parameters with the _searchPeople()_ function.  In order to use this function you'll need to apply for the Vetted API Access with your own developer account credentials.
